// USER
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_USER = "UPDATE_USER";

export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_ERROR = "GET_BOOKS_ERROR";

export const GET_BOOK_REQUEST = "GET_BOOK_REQUEST";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_ERROR = "GET_BOOK_ERROR";

export const VOTE_BOOK_REQUEST = "VOTE_BOOK_REQUEST";
export const VOTE_BOOK_SUCCESS = "VOTE_BOOK_SUCCESS";
export const VOTE_BOOK_ERROR = "VOTE_BOOK_ERROR";

export const SET_FILTERS = "SET_FILTERS";
export const SET_SOCKET = "SET_SOCKET";

export const SET_ERROR = "SET_ERROR";
export const DROP_ERROR = "DROP_ERROR";
